import axios from 'axios'
import { message } from 'antd'
import moment from 'moment'

const list = [
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 1,
    name: 'eri',
    email: 'test@test.com',
    lastName: 'dervishi',
    patientProfile: null,
    isActive: 1,
    birthday: '1991-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 1,
    credit: 1,
    isFormRead: 0,
    userId: 1,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 2,
    name: 'klea',
    email: 'test5@test.com',
    lastName: 'huta',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 5,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 3,
    name: 'mira',
    email: 'test6@test.com',
    lastName: 'abra',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 6,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 4,
    name: 'loni',
    email: 'test7@test.com',
    lastName: 'hajdari',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 7,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 1,
    name: 'eri',
    email: 'test@test.com',
    lastName: 'dervishi',
    patientProfile: null,
    isActive: 1,
    birthday: '1991-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 1,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 2,
    name: 'klea',
    email: 'test5@test.com',
    lastName: 'huta',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 5,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 3,
    name: 'mira',
    email: 'test6@test.com',
    lastName: 'abra',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 6,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 4,
    name: 'loni',
    email: 'test7@test.com',
    lastName: 'hajdari',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 7,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 1,
    name: 'eri',
    email: 'test@test.com',
    lastName: 'dervishi',
    patientProfile: null,
    isActive: 1,
    birthday: '1991-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 1,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 2,
    name: 'klea',
    email: 'test5@test.com',
    lastName: 'huta',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 5,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 3,
    name: 'mira',
    email: 'test6@test.com',
    lastName: 'abra',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 6,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 4,
    name: 'loni',
    email: 'test7@test.com',
    lastName: 'hajdari',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 7,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 1,
    name: 'eri',
    email: 'test@test.com',
    lastName: 'dervishi',
    patientProfile: null,
    isActive: 1,
    birthday: '1991-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 1,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 2,
    name: 'klea',
    email: 'test5@test.com',
    lastName: 'huta',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 5,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 3,
    name: 'mira',
    email: 'test6@test.com',
    lastName: 'abra',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 6,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 4,
    name: 'loni',
    email: 'test7@test.com',
    lastName: 'hajdari',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 7,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 1,
    name: 'eri',
    email: 'test@test.com',
    lastName: 'dervishi',
    patientProfile: null,
    isActive: 1,
    birthday: '1991-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 1,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 2,
    name: 'klea',
    email: 'test5@test.com',
    lastName: 'huta',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 5,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 3,
    name: 'mira',
    email: 'test6@test.com',
    lastName: 'abra',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 6,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 4,
    name: 'loni',
    email: 'test7@test.com',
    lastName: 'hajdari',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 7,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 1,
    name: 'eri',
    email: 'test@test.com',
    lastName: 'dervishi',
    patientProfile: null,
    isActive: 1,
    birthday: '1991-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 1,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 2,
    name: 'klea',
    email: 'test5@test.com',
    lastName: 'huta',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 5,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 3,
    name: 'mira',
    email: 'test6@test.com',
    lastName: 'abra',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 6,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 4,
    name: 'loni',
    email: 'test7@test.com',
    lastName: 'hajdari',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 7,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 1,
    name: 'eri',
    email: 'test@test.com',
    lastName: 'dervishi',
    patientProfile: null,
    isActive: 1,
    birthday: '1991-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 1,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 2,
    name: 'klea',
    email: 'test5@test.com',
    lastName: 'huta',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 5,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 3,
    name: 'mira',
    email: 'test6@test.com',
    lastName: 'abra',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 6,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 4,
    name: 'loni',
    email: 'test7@test.com',
    lastName: 'hajdari',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 7,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 1,
    name: 'eri',
    email: 'test@test.com',
    lastName: 'dervishi',
    patientProfile: null,
    isActive: 1,
    birthday: '1991-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 1,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 2,
    name: 'klea',
    email: 'test5@test.com',
    lastName: 'huta',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 5,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 3,
    name: 'mira',
    email: 'test6@test.com',
    lastName: 'abra',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 6,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 4,
    name: 'loni',
    email: 'test7@test.com',
    lastName: 'hajdari',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 7,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 1,
    name: 'eri',
    email: 'test@test.com',
    lastName: 'dervishi',
    patientProfile: null,
    isActive: 1,
    birthday: '1991-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 1,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 2,
    name: 'klea',
    email: 'test5@test.com',
    lastName: 'huta',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 5,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 3,
    name: 'mira',
    email: 'test6@test.com',
    lastName: 'abra',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 6,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 4,
    name: 'loni',
    email: 'test7@test.com',
    lastName: 'hajdari',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 7,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 1,
    name: 'eri',
    email: 'test@test.com',
    lastName: 'dervishi',
    patientProfile: null,
    isActive: 1,
    birthday: '1991-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 1,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 2,
    name: 'klea',
    email: 'test5@test.com',
    lastName: 'huta',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 5,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 3,
    name: 'mira',
    email: 'test6@test.com',
    lastName: 'abra',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 6,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 4,
    name: 'loni',
    email: 'test7@test.com',
    lastName: 'hajdari',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 7,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 1,
    name: 'eri',
    email: 'test@test.com',
    lastName: 'dervishi',
    patientProfile: null,
    isActive: 1,
    birthday: '1991-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 1,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 2,
    name: 'klea',
    email: 'test5@test.com',
    lastName: 'huta',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 5,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 3,
    name: 'mira',
    email: 'test6@test.com',
    lastName: 'abra',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 6,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 4,
    name: 'loni',
    email: 'test7@test.com',
    lastName: 'hajdari',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 7,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 1,
    name: 'eri',
    email: 'test@test.com',
    lastName: 'dervishi',
    patientProfile: null,
    isActive: 1,
    birthday: '1991-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 1,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 2,
    name: 'klea',
    email: 'test5@test.com',
    lastName: 'huta',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 5,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 3,
    name: 'mira',
    email: 'test6@test.com',
    lastName: 'abra',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 6,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 4,
    name: 'loni',
    email: 'test7@test.com',
    lastName: 'hajdari',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 7,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 1,
    name: 'eri',
    email: 'test@test.com',
    lastName: 'dervishi',
    patientProfile: null,
    isActive: 1,
    birthday: '1991-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 1,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 2,
    name: 'klea',
    email: 'test5@test.com',
    lastName: 'huta',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 5,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 3,
    name: 'mira',
    email: 'test6@test.com',
    lastName: 'abra',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 6,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 4,
    name: 'loni',
    email: 'test7@test.com',
    lastName: 'hajdari',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 7,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 1,
    name: 'eri',
    email: 'test@test.com',
    lastName: 'dervishi',
    patientProfile: null,
    isActive: 1,
    birthday: '1991-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 1,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 2,
    name: 'klea',
    email: 'test5@test.com',
    lastName: 'huta',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 5,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 3,
    name: 'mira',
    email: 'test6@test.com',
    lastName: 'abra',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 6,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 4,
    name: 'loni',
    email: 'test7@test.com',
    lastName: 'hajdari',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 7,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 1,
    name: 'eri',
    email: 'test@test.com',
    lastName: 'dervishi',
    patientProfile: null,
    isActive: 1,
    birthday: '1991-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 1,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 2,
    name: 'klea',
    email: 'test5@test.com',
    lastName: 'huta',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 5,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 3,
    name: 'mira',
    email: 'test6@test.com',
    lastName: 'abra',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 6,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 4,
    name: 'loni',
    email: 'test7@test.com',
    lastName: 'hajdari',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 7,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 1,
    name: 'eri',
    email: 'test@test.com',
    lastName: 'dervishi',
    patientProfile: null,
    isActive: 1,
    birthday: '1991-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 1,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 2,
    name: 'klea',
    email: 'test5@test.com',
    lastName: 'huta',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 5,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 3,
    name: 'mira',
    email: 'test6@test.com',
    lastName: 'abra',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 6,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
  {
    createdAt: '2022-08-05T22:43:37.843Z',
    updatedAt: '2022-08-05T22:43:37.843Z',
    id: 4,
    name: 'loni',
    email: 'test7@test.com',
    lastName: 'hajdari',
    patientProfile: null,
    isActive: 1,
    birthday: '1994-12-11T23:42:07.000Z',
    form: 'test',
    role: 'patient',
    verificationCode: '280383',
    isSingle: 0,
    credit: 1,
    isFormRead: 0,
    userId: 7,
    details: {
      time: 'La sera dalle 18:00 alle 20:00 (ora italiana)',
      phone: '+3969393910',
      referral: 'Ho visto la vostra pagina Facebook o Instagram',
      motivation: 'cover',
      preference: 'Che il mio psicologo sia uomo',
      question_1: ['Provo spesso ansia o stress'],
      question_2: ['Non ho un buon rapporto con il mio corpo e/o con il cibo'],
      question_3: ['Vorrei conoscermi meglio'],
      question_4: ['Vorrei conoscermi meglio'],
      preferedDay: 'Martedí',
      requiredTime: 'La mattina dalle 8:00 alle 13:00 (ora italiana)',
      agePreference: 'Che sia il più adatto a sostenermi',
      doubts_questions: 'domande',
      alternativePreferedDay: 'Giovedí',
    },
    status: 'registrato',
    freeTrial: 'da programmare',
    consent: null,
    newsletter: 0,
  },
]

export const getPatients = async () => {
  return { data: list }
  // return await axios
  //   .get('/sessions/patients')
  //   .then(response => ({ error: false, data: response.data.patients }))
  //   .catch(e => ({ error: true, msg: e.response?.data?.error?.message || 'Something went wrong!' }))
}

export const getAllSessions = async year => {
  const allSessions = await axios
    .get(`/sessions/all?year=${year}`)
    .then(response => response.data.allSessions)
    .catch(e => {
      message.error(e.response?.data?.error?.message || 'Something went wrong!')
      return []
    })
  const session = allSessions.reduce((o, { amount, isConfirmed, month, done }) => {
    o[month] = o[month] || { confirmed: 0, unConfirmed: 0, done: 0 }
    o[month][isConfirmed ? 'confirmed' : 'unConfirmed'] += +amount
    o[month].done += +done
    return o
  }, {})
  const monthsNames = moment.months()
  return monthsNames.map((m, i) => ({ name: `${m} ${year}`, ...session[i + 1] }))
}

export const getSessions = async month => {
  const sessions = await axios
    .get(`/sessions/my-agenda?month=${month}`)
    .then(response => response.data.allSessions)
    .catch(e => {
      message.error(e.response?.data?.error?.message || 'Something went wrong!')
      return []
    })
  return sessions
}
